version: '3.8'

services:
  postgres:
    container_name: pgdb
    image: ${POSTGRES_DEFAULT_IMAGE}
    environment:
      POSTGRES_USER: ${POSTGRES_DEFAULT_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_DEFAULT_DOCKER_PORT}:${POSTGRES_DEFAULT_LOCAL_PORT}"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: ${PGADMIN_DEFAULT_IMAGE}
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_DEFAULT_DOCKER_PORT}:${PGADMIN_DEFAULT_LOCAL_PORT}"
    networks:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-changeme}
    restart: unless-stopped

volumes:
    postgres:

networks:
  postgres:
    driver: bridge